### ISSUE TITLE
부족한 분량으로 fine-tuning

### ISSUE THREAD

**Issue by jhwanflow** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#10]
안녕하세요,

올려주신 repo 덕분에, 음성합성 모델을 구현하는데 많은 도움이 되고 있습니다.

혹시 pre-trained 모델 위에 새로운 데이터셋을 적용하여 fine-tuning을 하면,

음성샘플의 총 분량이 기존 데이터셋에 비하여 현저히 부족하더라도, 학습이 잘 될 수 있을까요?

예를 들어, 현재 구현된 fastspeech2 모델은 약 12.5시간의 분량인 kss데이터셋으로 학습된걸로 알고 있습니다. 

그렇다면 이 기존 모델위에 30분~1시간 정도 분량의 제 목소리로 fine-tuning을 시킨다면, 제 목소리로 tts가 가능할까요?

**Comment by Jackson-Kang** [comment]
안녕하세요, @JH-lee95 님.

요근래 일이 많아 답장이 늦었습니다.
답변이 늦어 정말 죄송합니다.

질문주신 사항에 답변 드립니다.

일반적으로 transfer-learning은 pretraining을 통해 모델에 학습될 data의 확률분포가
finetune할때의 data의 확률분포와 비슷할 때 좋은 성능을 기록합니다.

그러므로, "제 의견"은 pretraining 할 때 사용된 dataset의 확률분포와 @JH-lee95 님 목소리로 구성된 dataset의 확률분포가 비슷하다면 말씀하신 사항이 충분히 가능합니다. (확률 분포의 유사도가 클 수록 성능이 좋을 가능성이 높습니다.)

또한, finetune시 필요한 dataset의 분량도 비슷한 문제라고 생각됩니다.
일반적인 관점에서, 확률 분포의 유사도가 클수록 필요한 dataset의 수는 적어도 될 가능성이 높습니다.


답변이 도움이 되셨으면 좋겠습니다.
감사합니다.

**Comment by jhwanflow** [comment]
바쁘신 와중에 답변해주셔서 감사합니다! 이슈는 닫을게요!
