### ISSUE TITLE
g2pk로 duration 추출 후 fastspeech2 훈련 시 나오는 Incompatible shapes 에러

### ISSUE THREAD

**Issue by lsh950919** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#12]
안녕하세요.

먼저 fastspeech2에 대한 자세한 설명 감사드립니다.

현재 이 [repo](https://github.com/TensorSpeech/TensorFlowTTS)의 FastSpeech2 모델을 저희가 가지고 있는 데이터셋으로 fine tuning 하는 과정에서 Jackson Kang님이 올려주신 방식대로 g2pk를 사용해 duration을 추출하는 것까지는 완료 된 상황입니다.

그런데 이 파일을 가지고 train valid split을 진행한 후에 모델 훈련을 하려고 하니 Incompatible shapes 에러가 발생하면서 훈련을 진행되지 않는 현상이 발생됩니다.

처음 이 문제가 발생 했을 때는 sample rate의 문제일까 싶어 down sampling도 진행해 보았으나 같은 문제가 계속 반복되고 있고, 위 repository의 fix_mismatch라는 코드가 문제인가 싶어 train valid split을 직접 나눠 실행 했을 때도 되지 않아 막혀있는 상태입니다.

데이터는 5-10초 가량의 음성 120개를 사용중인데, corpus가 너무 작은 문제일수도 있을까요?

이 에러가 왜 발생하는지, 어떻게 고칠 수 있는지 아시는게 있으면 도와주시면 감사하겠습니다.

에러 메세지는 아래에 있습니다.

![error](https://user-images.githubusercontent.com/52195373/117394092-7586ed80-af30-11eb-8eb6-7c9a382054f6.png)

**Comment by Jackson-Kang** [comment]
@lsh950919 님께,

안녕하세요, @lsh950919 님.

제가 "TensorflowTTS"를 사용해본 적이 없어 정확히 답변을 드리기는 어렵지만, 아래 사항을 한번 점검해 보시겠어요?

* FastSpeech2의 Encoder의 input으로 들어가는 것이 phoneme sequence임을 확인
* FastSpeech2 Encoder의 input으로 MFA에서 추출된 phoneme sequence가 들어가는지 확인



감사합니다.

**Comment by lsh950919** [comment]
감사합니다 @Jackson-Kang 님!

한번 확인 해보도록 하겠습니다.

이 이슈는 닫겠습니다.
