### ISSUE TITLE
전이학습에 관한 질문

### ISSUE THREAD

**Issue by jhwanflow** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#13]
안녕하세요,  

올려주신 Pretrained model을 이용하여

제가 가진 커스텀데이터셋으로 

전이학습을 하여 일종의 음성복제를 해보려고 합니다.

이 경우에 체크포인트만 설정하고, 그냥 학습을 이어서 진행하면 되는 것일까요?

아니면 따로 설정해주어야 하는 것이 있나요?

**Comment by Jackson-Kang** [comment]
@JH-lee95 님께,


안녕하세요, @JH-lee95 님.

pretraining 완료 후, finetuning시 learning rate를 낮춰서 학습하시면 큰 문제 없이 동작 가능하리라 생각됩니다.
다만, JH-lee95님이 가진 커스텀 데이터셋과 kss dataset의 확률분포가 비슷해야 효과적인 학습이 가능합니다.

감사합니다.

**Comment by jhwanflow** [comment]
바쁘실텐데 지속적으로 답변해주셔서 감사드립니다!

Learning rate의 경우 최종 step에서의 learning rate를 이용하면 될까요?

또한 음성 데이터의 확률분포는 어떻게 파악할 수 있을까요?

**Comment by Jackson-Kang** [comment]
> 바쁘실텐데 지속적으로 답변해주셔서 감사드립니다!
> 
> Learning rate의 경우 최종 step에서의 learning rate를 이용하면 될까요?
> 
> 또한 음성 데이터의 확률분포는 어떻게 파악할 수 있을까요?

안녕하세요, @JH-lee95 님.
질문주신 사항에 답변드립니다.

Learning rate는 적당히 낮은 값으로 주시면 됩니다. 얼마만큼 주어야 적절한지는 실험적으로 알아내셔야 합니다. 너무 낮아도 finetune시 학습이 오래 걸립니다. 

음성 데이터의 latent space상 확률 분포는 파악하기 어렵습니다. Dataset마다 확률분포의 차이가 크고, 매우 고차원공간에 나타나기 때문입니다. 

사전학습 데이터에 영향이 큰 transfer learning의 특성상, 학습을 한번 해 보시고 finetune한 모델이 생성하는 음성이 custom dataset과 유사한지, kss와 유사한지를 보시기를 추천드립니다.

부족하지만, 답변이 도움이 되셨으면 좋겠습니다.
감사합니다.

**Comment by Jackson-Kang** [comment]
오랜 기간 활성화되지 않은 issue이므로, 본 issue를 close합니다.
다른 질문 있으시면 다시 이 issue를 reopen해 주시기 바랍니다.

감사합니다.
