### ISSUE TITLE
경로문제...

### ISSUE THREAD

**Issue by choiHkk** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#18]
감사합니다

**Comment by Jackson-Kang** [comment]
안녕하세요, @choiHkk 님.

혹시 경로 관련 어떤 문제가 발생한다는 말씀이신지 여쭤봐도 될까요?

감사합니다.

**Comment by choiHkk** [comment]
아닙니다:) 제 실수로 발생한 문제였습니다.

2022년 1월 2일 (일) 오후 12:39, Minsu Kang ***@***.***>님이 작성:

**Comment by Jackson-Kang** [comment]
네, 알겠습니다.
답변이 늦어 대단히 죄송합니다.

본 이슈는 닫겠습니다!..
감사합니다.

**Comment by choiHkk** [comment]
아닙니다! 혼란 드려서 죄송합니다.

2022년 1월 2일 (일) 오후 1:07, Minsu Kang ***@***.***>님이 작성:
