### ISSUE TITLE
생성 된 음성에서 띄어 읽기와 연음 문제 관련 문의

### ISSUE THREAD

**Issue by ChangNamAn** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#19]
안녕하세요.
공유해주신 코드 잘 활용하고 있는데요.

1. 좀 긴 문장을 입력으로 받게 되면 생성된 음성에서 띄어 읽기가 잘 안되어 어색하게 들립니다.
현재 입력으로 받은 문장에서 마침표를 띄어 읽기 {sp}로 바꾸게 되어 있는데요. 이렇다 보니 나머지들은 거의 붙여서 읽게 되더군요.
혹시 해결 방안이나 아이디어가 있을까요?
강제로 공백 부분을 {sp}로 변경도 해보았는데 이 역시 해결 방법은 아니더군요.

혹시 조언을 얻을 수 있을까요?

미리 감사드립니다.

**Comment by Jackson-Kang** [comment]
안녕하세요, @ChangNamAn 님.
답변이 늦어 대단히 죄송합니다.

혹시 dataset을 변경하셨거나, 변경된 dataset에서 alignment를 따로 얻어서 본 모델을 학습하신건가요?
아니면, 저희가 제공해드린 pretrained model을 사용하신건가요?..

감사합니다.

**Comment by ChangNamAn** [comment]
@Jackson-Kang 님,
dataset을 변경하였고 변경된 dataset으로 alignment를 따로 얻어서 학습시켰습니다.

**Comment by Jackson-Kang** [comment]
@ChangNamAn 님께,

alignment를 추출하기 위해 MFA를 학습하는 과정에 대해 질문드립니다.
MFA 학습시 ","나 "."등의 token들이 "sp" token으로 변경되어 alignment가 추출 되는 것인가요?

**Comment by Jackson-Kang** [comment]
오랜 기간 discussion이 없어 issue를 닫겠습니다.
추후 재 논의시에 reopen 부탁드립니다.

감사합니다.
