### ISSUE TITLE
could you upload audio samples generated from this repo?

### ISSUE THREAD

**Issue by byuns9334** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#2]
thanks!

**Comment by Jackson-Kang** [comment]
Hello @byuns9334 ,

I have just uploaded audio samples on my soundcloud storage.
Please refer updated README.md and listen them.

Thank you for asking question.
Sincerely,

**Comment by Jackson-Kang** [comment]
For your convenience, refer the link below.

https://soundcloud.com/7vwcti7og4fp/sets/korean-fastspeech2-audio-samples


Thank you.
