### ISSUE TITLE
음성 합성 오류

### ISSUE THREAD

**Issue by oldkimchi** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#21]
kss데이터셋으로 preprocess 후 train을 실행하였고 synthesize 실행 결과
왼쪽이 결과이고 오른쪽이 pre-trained model 결과입니다.

<img width="668" alt="specto" src="https://user-images.githubusercontent.com/45351939/168952514-8007ccbd-94e7-4c18-a2ac-38f9b3b4427d.png">

제대로된 음성으로 합성이 안되고 발음을 알수없는 음성으로 나오는데 혹시 무엇을 개선해야될지 궁금합니다
아래 음성파일이 학습하여 합성한 음성입니다.
https://user-images.githubusercontent.com/45351939/168953348-044a4317-2de2-4881-b6cb-5eb7c76f37ec.mp4

**Comment by oldkimchi** [comment]
합성한 오디오파일 스펙입니다
<img width="647" alt="image" src="https://user-images.githubusercontent.com/45351939/168953862-c71c23db-ed00-4fa3-a32f-5761349e1233.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/45351939/168953887-49d50a4a-9c1a-4b09-a9ac-c88f284a4a9f.png">

**Comment by oldkimchi** [comment]
kss.py 의 line 97,98     
f0, energy = remove_outlier(f0), remove_outlier(energy)
f0, energy = average_by_duration(f0, duration), average_by_duration(energy, duration)
이 부분에서 너무작은 f0의 값이 이상치로 치부되 삭제되는 부분을 확인하고
 if np.all(f000 == 0):
        print("f0======0")
        wav, _ = librosa.load(wav_path,sr = 22050)
        f0 = librosa.yin(wav,sr=22050,fmin = librosa.note_to_hz("C2"),fmax= librosa.note_to_hz("C7"))
        f0 = f0[:sum(duration)]
        f0, energy = remove_outlier(f0), remove_outlier(energy)
        f0, energy = average_by_duration(f0, duration), average_by_duration(energy, duration)
을 line 98 다음에 추가해 preprocess.py 가 오류없이 돌아가게 하였습니다. 이거말곤 고친 부분이 없는데 합성이 이상하게 나옵니다.

**Comment by Jackson-Kang** [comment]
안녕하세요, @oldkimchi 님.

군사교육으로 인해 훈련소에 입소하여 
이슈를 늦게 확인하였습니다.

답변이 늦어 죄송합니다.

혹시 문제가 해결 되셨는지요?
