### ISSUE TITLE
합성음 control 방법

### ISSUE THREAD

**Issue by Moon-sung-woo** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#22]
안녕하세요.
먼저 멋진 코드를 공유해주셔서 감사합니다.
올려주신 코드를 보며 control가능한 음성합성기를 만들고 있습니다.

@ming024/Fastspeech를 보면 synthesize.py에서 pitch, energy, duration에 대한 값을 지정하여 합성음에 대해 control하는 코드를 확인할 수 있었습니다.
하지만 @Jackson-Kang 님이 올려주신 코드를 보면 합성 model과 synthesize 부분에 따로 pitch, energy, duration에 대한 파라미터 값을 주지 않는 것으로 봤습니다.

1. 올려주신 코드로 pitch, duration, energy을 control할 수 있을까요?
2. 만약 하지 못한다면 어느 부분을 수정해 주는 게 좋을지 알려주시면 감사하겠습니다.

감사합니다.

**Comment by Jackson-Kang** [comment]
안녕하세요, @Moon-sung-woo 님.

육군훈련소 입소로 인해 답변이 늦었습니다.
답변을 늦게 드려 죄송합니다.

혹시 관련 문제가 해결 되셨는지요?

**Comment by Moon-sung-woo** [comment]
안녕하세요 @Jackson-Kang 님.
훈련 받으시느라 고생하셨네요 ㅠㅠ
https://github.com/ming024/FastSpeech2의 코드를 참고하여 새로 학습 진행하고 있습니다!
혹시 @Jackson-Kang 님 코드로도 control가능 할지요?

**Comment by Jackson-Kang** [comment]
안녕하세요, @Moon-sung-woo 님.

하루~이틀 내로 코드 점검 후 control 기능 지원하도록 변경 후 답변 드리겠습니다.
감사합니다.

**Comment by Moon-sung-woo** [comment]
안녕하세요 @Jackson-Kang 님.
코드 지원 정말 감사합니다.

참고하신 [ming024 fastspeech](https://github.com/ming024/FastSpeech2)의 코드를 보면 loss계산 하시는 방법이 @Jackson-Kang 님과 달라 질문이 있습니다.

참고하신 ming024님의 loss 계산에는 mel_loss, postnet_mel_loss에는 mae_loss를 pitch_loss, energy_loss, duration_loss에는 mse_loss를 사용했습니다. 
하지만 @Jackson-Kang 님의 loss계산에는 mel_loss, postnet_mel_loss에는 mse_loss pitch_loss, energy_loss, duration_loss에는 mae_loss를 사용하셨는데 이유가 있을까요??

**Comment by Jackson-Kang** [comment]
안녕하세요, @Moon-sung-woo 님!
코드 업데이트가 늦어 죄송합니다.

controllable한 음성 조절이 가능하도록 기능을 추가하였습니다.
업데이트된 코드의 synthesize.py의 [dur_pitch_energy_aug](https://github.com/HGU-DLLAB/Korean-FastSpeech2-Pytorch/blob/8f4e546facc22e4e833120f3343077debd0d8250/synthesize.py#L98)를 조절하셔서 control 가능합니다.

질문 주신 loss 관련 issue는 [링크](https://github.com/HGU-DLLAB/Korean-FastSpeech2-Pytorch/pull/6)를 참조해 주시면 감사하겠습니다!

감사합니다.

**Comment by Moon-sung-woo** [comment]
답변 감사합니다. @Jackson-Kang 님!
답변주신 내용을 토대로 개발해보도록 하겠습니다.

감사합니다.
