### ISSUE TITLE
제공 해준 TextGrid와 직접 만든 TextGrid의 서로 다른 문제

### ISSUE THREAD

**Issue by jenginsu** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#23]
안녕하세요? 이렇게 잘 정리 해주셔서 감사합니다.

제 질문은
선생님께서 제공해주신 TextGrid와 제가 KSS 1.4로 만든 TextGrid 부분에서 차이가 발생하여 질문을 드립니다.

저의 MFA를 만들기 위한 환경
ㄴ conda 가상환경 & Python 3.8.13 & 기타 등등(requirements.txt의 버전을 꼭 맞추지는 않음)

질문 1. 1_0001.TextGrid 내부를 보면 값들이 서로 약간 다릅니다. 
        어떤 TextGrid는 음소를 인식못하여 정상적으로 파일을 못 만드는것 같은것도 있는것 같습니다.> 원인이 뭘까요?
질문 2. 전체 음성 갯수 중에 약 5개정도 TextGrid 파일이 만들어 지지 않았는데  이부분은 빼고 preprocess.py를 돌려도 되는지요?
질문 3: TextGrid 이 부분이 train.py 이후에 나오는 *.pth.tar의 음성합성 결과에 많은 영향을 미칠까요? > 학습을 오래 시켜도 기 제공해 준 checkpoint_350000.pth.tar는 음성합성 결과가 좋은데, 제가 만든것은 좀 엉망(실망) 수준이거던요;;

MFA 부터 잘못 된것이라면 다시 살펴 보도록 하겠습니다.
고맙습니다.

**Comment by Jackson-Kang** [comment]
안녕하세요, @jenginsu 님.
먼저, 본 repository에 관심을 가져 주셔서 감사드립니다.

질문하신 사항에 답변을 드립니다.

답변 1. 말씀하신 사항은 (1) 한글 grapheme을 phoneme으로 변경한 g2p 모듈의 차이, 혹은 (2) MFA 버전의 다름으로 인해 발생하는 문제인 듯 합니다. 본 repository에서 쓴 g2p 모듈은  [g2pk](https://github.com/Kyubyong/g2pK)를 사용하였고, ```MFA 1.0```을 사용하였습니다. 현재는 MFA 버전이 많이 업데이트 되어 제가 사용한 버전과 차이가 있을 듯 합니다.

답변 2. 문제가 있는 5개의 TextGrid를 제외한 나머지 TextGrid에 기입된 샘플별 mel-text alignment가 제대로 추출 되었는지 확인이 필요할 듯 합니다. 만약 그렇다면, 5개의 샘플을 학습에서 제외하는 것은 큰 문제가 되지 않을 듯 합니다.

답변 3. FastSpeech2는 explicit하게 duration을 예측하는 duration predictor가 존재합니다. 학습시, MFA에서 예측된 text-mel alignment(duration)을 정답으로 하여 duration predictor가 학습됩니다. 만약 TextGrid에 기입된 text-mel alignment 정보가 정확하지 않다면, 다음과 같은 문제가 발생할 가능성이 높습니다.
     (1) 잘못된 음소별 발음길이를 예측하게 되어, 발음이 정확하지  않게 됨
     (2) 잘못 예측된 발음 정보를 토대로 pitch와 energy 정보를 예측/반영하게 되어 합성시 좋은 품질의 음성 생성이 어려움.


부족한 답변이 도움이 되었으면 좋겠습니다.
감사합니다.

**Comment by jenginsu** [comment]
답변 감사합니다. 어떤 차이로 문제가 있는지 열심히 찾아 보겠습니다^^

**Comment by Jackson-Kang** [comment]
@jenginsu 님께,

다른 질문이 있다면, 언제든 문의 주시기 바랍니다.
감사합니다 :)
