### ISSUE TITLE
mfa acoustic model을 훈련하기 위해 어떤 데이터셋을 사용하셨는지 여쭤봐도 될까요?

### ISSUE THREAD

**Issue by SeongYeonPark** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#24]
안녕하세요.

제공해주신 textgrid와 kss 데이터셋을 이용하여 본 모델을 훈련해보니, 긴 문장에 대해서도 안정적인 합성이 이루어짐을 확인했습니다.
다른 소프트웨어로 확인한 textgrid의 align 품질도 매우 정확했구요.

그런데 제가 직접 훈련한 mfa acoustic model로 textgrid를 추출해보면, textgrid의 align 품질이 정확하지 않은 부분들이 다소 보이며, (이것이 직접적인 원인이 된건지는 몰라도) 긴 문장을 합성할 때에 있어 안정성이 매우 떨어졌습니다.

mfa acoustic 모델을 훈련하기 위해 다음 데이터셋들을 사용해봤습니다.
- AIHub Multimodal Video AI datasets
- KSS dataset
- zeroth korean dataset
하지만 위의 데이터셋들로 훈련해본 acoustic 모델 모두 kss에서의 textgrid align 정확도가 좋지 않았습니다.

혹시 제공해주신 textgrid를 추출하기 위해 어떤 데이터셋으로 mfa acoustic model을 훈련하셨는지 여쭤봐도 될까요?

**Comment by Jackson-Kang** [comment]
안녕하세요, @SeongYeonPark 님.
먼저, 본 프로젝트에 관심을 가져 주셔서 감사드립니다.


제가 학습한 MFA 모델은 KSS dataset만 사용하여 학습하였으며, 다른 dataset은 사용하지 않았습니다.

동작 원리상, MFA acoustic model은 speech data의 diversity가 높아지면 (i.e., speaker, emotion 등 dataset의 variation을 높이는 요소가 많아지면) 잘 동작하지 않거나, 혹은 잘 동작하게 만들기 위해 tuning 하기 어려울 것이라 (개인적으로는) 생각했기 때문입니다.

아래 두 이슈를 참고하시면, 원하시는 정확한 alignment를 얻을 수 있지 않을까 생각합니다.

https://github.com/HGU-DLLAB/Korean-FastSpeech2-Pytorch/issues/23 ,  https://github.com/HGU-DLLAB/Korean-FastSpeech2-Pytorch/issues/25


부족한 답변이 도움이 되었으면 좋겠습니다.
감사합니다.

**Comment by Jackson-Kang** [comment]
오랜 기간 활동이 없어, 본 issue는 close하도록 하겠습니다.
다른 질문이 있으시면 reopen해주신 후 질문 주시면 감사하겠습니다.

감사합니다.
