### ISSUE TITLE
TextGrid 만들기 관련 질문 드립니다.

### ISSUE THREAD

**Issue by jenginsu** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#25]
안녕하세요. 
지금 현재로써는, FastSpeech2는 TextGrid를 얼마나 잘 만드냐에 달린 문제인것 같습니다.(나머지 부분은 쉽게 해결..)

이곳에 두번째 질문을 드립니다.

1) lab 파일 만들 때 transcript.v.1.4.txt의 "|"를 split할 때 몇 번째를 lab 파일로 사용하셨는지요?
    ㄴ 0번째는 파일정보, 1번째는 숫자포함 정보, 2번째는 숫자를 한글로 표시한 정보, 3번째는 2번째와 비슷하지만 캐릭터 셋이 좀 다름

2) 현재 conda에서 MFA를 설치하면 2.0.5까지 설치가 됩니다. 저번 질문의 답변에서 MFA 1.0버전을 사용 했다고 하여
    MFA 1.0.1을 다운로드하여 설치하고 g2pk를 이용하여 TextGrid를 만들어 보는데 잘 안만들어 지네요.
    혹시 공개 해주신 TextGrid를 만드는 명령어나  순서 등등 아무것이라도 뭐 그런것 자료가 있으면 공유 해주실 수 있을까요?

참고: MFA 2.0.5에서 나름 준수하게 TextGrid를 만들기는 했습니다(https://chldkato.tistory.com/195 참고하여.)
         그런데 g2pk를 사용하여 lab 파일을 만들면  몇 번째 텍스트 정보를 사용하든 오류가 발생해서,
         3번째 텍스트(캐릭터셋이 좀 다른것)를 이용하되 g2pk를 적용하지 않고 만들어 학습을 하고 있습니다.
         예) 괜찮은척 하려고
               g2pk를 사용: ㄱㅗㅐㄴㅊㅏㄴㅡㄴㅊㅓㄱㅋㅏㄹㅕㄱㅗ(사람이 소리 나는대로 TextGrid에 음소 표시됨)
                g2pk를 사용안함: ㄱㅗㅐㄴㅊㅏㄶㅇㅡㄴㅊㅓㄱㅎㅏㄹㅕㄱㅗ(자소라고 하나요? 아주 정직하게 TextGrid에 표시됨)
          어찌되었던 g2pk를 사용안하더라도, synthesize에서도 g2pk를 타지 않고 음성 합성하면 되지 않을까 하여 학습은 진행중입니다.
           그리나 해당 모델을 이용 음성 합성하니, 좀 엉망으로 나오네요(너무 정직하게 읽다보니 발음이 자연스럽지가 않네요.)

conda 가상환경으로 python3.7 및 MFA 1.0.1 버전까지 설치하고 TextGrid를 만들어 보았는데, 공유해주신 TextGrid와는 달라서 
너무 답답합니다.
에전 TextGrid 만든 흔적이라도 있음 공유해주시면 정말 많은 도움이 될것 같습니다.
이 문제로 너무 스트레스를 받네요;;

읽어 주셔서 고맙습니다.

**Comment by Jackson-Kang** [comment]
@jenginsu 님께,

안녕하세요, @jenginsu 님.
질문주신 사항에 대한 답변 드립니다.

Q-1. lab 파일 만들 때 transcript.v.1.4.txt의 "|"를 split할 때 몇 번째를 lab 파일로 사용하셨는지요?
ㄴ 0번째는 파일정보, 1번째는 숫자포함 정보, 2번째는 숫자를 한글로 표시한 정보, 3번째는 2번째와 비슷하지만 캐릭터 셋이 좀 다름

A-1) Decomposed script (3번째-0을 시작으로 했을 경우)를 사용하여 학습했습니다.


Q-2. 현재 conda에서 MFA를 설치하면 2.0.5까지 설치가 됩니다. 저번 질문의 답변에서 MFA 1.0버전을 사용 했다고 하여 MFA 1.0.1을 다운로드하여 설치하고 g2pk를 이용하여 TextGrid를 만들어 보는데 잘 안만들어 지네요.
혹시 공개 해주신 TextGrid를 만드는 명령어나 순서 등등 아무것이라도 뭐 그런것 자료가 있으면 공유 해주실 수 있을까요?

A-2) 관련해서, 제가 사전에 작성한 코드가 있습니다.

https://github.com/Jackson-Kang/Korean-phoneme-dictionary-generator

KSS에 대한 코드는 없지만, 코드의 일부를 참고하시면, 원하시는 것에 도움이 되지 않을까 생각합니다.


부족하지만, 도움이 되었으면 좋겠습니다.
감사합니다.

**Comment by jenginsu** [comment]
고맙습니다. 많이 공부해서 꼭 성공해 보겠습니다^^
