### ISSUE TITLE
훈련 관련 문의

### ISSUE THREAD

**Issue by Moon-sung-woo** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#26]
안녕하세요!
올려주신 코드와 issue들의 답변을 보며 많이 배우고 있습니다.
감사합니다.

음성합성 학습 관련하여 질문이 있어 issue남기게 되었습니다.
음성합성 모델을 학습시킬 때 필요한 데이터에 대해 여쭤보고싶습니다.

  1. 학습 시키기 위한 필요 데이터 시간이 있을까요?? (많으면 많을수록 좋을 것 같지만 보통 몇시간 정도 데이터로 학습시킨다 정도 되는 지표가 있는지 궁금합니다.
  2. 음성 db를 만들 때 데이터의 포멧 또는 스텐다드가 있을까요? (예를 들어 팬그램...?)
  모든 발화가 이루어지는 문장 모음이라던지 또는 이와 관련된 논문 또는 키워드가 있는지 궁금합니다.
  3. 다화자 데이터셋을 이용한 학습방법 vs 단일 화자의 데이터셋 만을 이용한 학습방법 (단일화자의 데이터셋은 약 3시간 정도 있습니다)
  어떠한 방법이 더 좋은 것인지 모르겠습니다.

항상 자세하고 친절하게 답변 달아주셔서 너무 감사드립니다.
감사합니다.

**Comment by Jackson-Kang** [comment]
@Moon-sung-woo 님께,

안녕하세요 @Moon-sung-woo 님.

어떤 task에 대한 모델을 설계하고, 학습할 지에 따라 답변이 달라질 듯 합니다.
음성합성 모델을 어떤 task에 대해 설계하실 목적이신가요?

예 1. - 단일 화자 목소리를 잘 생성하는 고품질의 단일화자 음성합성 모델 개발
예 2. - 다화자 목소리를 잘 생성하는 다화자 음성합성 모델 개발

**Comment by Moon-sung-woo** [comment]
안녕하세요 @Jackson-Kang 님.

예 1번과 같은 단일 화자 목소리를 잘 생성하는 고품질의 단일화자 음성합성 모델을 개발하고 싶습니다.

감사합니다.

**Comment by Jackson-Kang** [comment]
안녕하세요, @Moon-sung-woo 님.
답변이 길어 메일로 질문에 대한 답변 드리겠습니다.

감사합니다.

**Comment by Moon-sung-woo** [comment]
안녕하세요 @Jackson-Kang 님.
추가 질문이 있어 메일 드렸습니다.

친절한 답변 정말 감사드립니다.

**Comment by Jackson-Kang** [comment]
본 issue는 메일로 답변을 드렸으므로, close하겠습니다.

감사합니다.
