### ISSUE TITLE
음질 개선 방법 중 vocoder관련 문의

### ISSUE THREAD

**Issue by Moon-sung-woo** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#28]
안녕하세요 @Jackson-Kang 님.
issues 중 [합성음의 품질을 올리는 방법](https://github.com/HGU-DLLAB/Korean-FastSpeech2-Pytorch/issues/16) 올려주셔서 감사합니다. 
품질음을 올리는 방법중 궁금한 것이 있어 issue남기게 되었습니다.

'2. Neural vocoder(VocGAN)을 오랜 시간동안 학습' 하셔서 성능을 올리셨다 하셨는데
vocoder학습 방법에 대해 질문이 있습니다.

공개되어 있는 모델(예 hifi-GAN)의 universal한 pre-trained모델을 이용하여 fine-tuning을 할 예정입니다.
이때 단일화자의 고품질 합성음을 얻고싶다면 단일화자의 dataset만을 이용하여 fine-tuning 시키는 것이 좋을지
아님 한국인들의 다양한 dataset과 얻고자 하는 화자의 dataset을 합쳐 학습시키는 것이 좋은지 모르겠습니다.

바쁘실텐데 항상 자세하고 친절한 답변 달아주셔 감사합니다.

**Comment by Jackson-Kang** [comment]
@Moon-sung-woo 님께,

안녕하세요, @Moon-sung-woo 님.

vocoder 성능 향상은 본 fastspeech2 implementation과는 무관하므로, 메일로 질문 주시면 감사하겠습니다.

본 issue는 close하겠습니다.
감사합니다.
