### ISSUE TITLE
preprocess.py에서 오류가 나는 문제

### ISSUE THREAD

**Issue by ruria0118** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#32]
절차에 따라서 preprocess.py를 실행하면 kss.py에서 오류가 발생합니다

Traceback (most recent call last):
  File "preprocess.py", line 63, in <module>
    main()
  File "preprocess.py", line 58, in main
    train, val = kss.build_from_path(in_dir, out_dir, meta)
  File "C:\Project\TTS3\data\kss.py", line 56, in build_from_path
    param_list = [np.array([scaler.mean_, scaler.scale_]) for scaler in scalers]
  File "C:\Project\TTS3\data\kss.py", line 56, in <listcomp>
    param_list = [np.array([scaler.mean_, scaler.scale_]) for scaler in scalers]
AttributeError: 'StandardScaler' object has no attribute 'mean_'

제가 찾아본 바로는 mean_ 값은 fit_transform에 data를 입력해야 나오는 것으로 알고있는데
def build_from_path(in_dir, out_dir, meta): 의 코드를 보면 mean_값이 나올만한 부분이 보이지 않습니다
혹시 코드상의 오류인지 제가 다른 부분에서 설정을 잘못 한 것인지 궁금합니다

**Comment by ruria0118** [comment]
제 설정이 잘못 됐던건지 이것저것 설치하다보니 해결됐습니다

**Comment by hannal** [comment]
@ruria0118 문제가 해결된 현 상태에서 사용하는 sklearn 버전이 몇인지 혹시 알 수 있을까요?

**Comment by jhss** [comment]
안녕하세요. 혹시 어떤 거 설치하셨는지 알려주실 수 있을까요? 저도 같은 오류가 발생했는데 해결이 안됩니다..
