### ISSUE TITLE
 Montreal Forced Aligner를 이용한 TextGrid를 생성하는 방법

### ISSUE THREAD

**Issue by hccho2** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#5]
먼저, 좋은 자료 공개해 주셔서 감사합니다.

 Montreal Forced Aligner를 이용하여, TextGrid를 생성하는 방법에 대한 설명 부탁드립니다.

**Comment by keonlee9420** [comment]
@hccho2 안녕하세요, 저도 MFA 학습을 비롯한 FastSpeech2에서의 한국어 데이터셋 처리 및 준비에 대해 시행착오를 겪었습니다. 이 repo와 선생님께서 제공해주신 내용([repo](https://github.com/hccho2/Tacotron2-Wavenet-Korean-TTS))에 더해 전반적인 한국어 processing 과정을 [이곳](https://github.com/keonlee9420/Emotional-FastSpeech2)에 정리해 두었으니 참고해 보시면 어떨까 합니다.
