### ISSUE TITLE
Question about G2P for TextGrid

### ISSUE THREAD

**Issue by Wonbin-Jung** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#8]
Hi I have a question about TextGrid from MFA.

In your TextGrid.zip in Gdrive, there are duration information of each Korean characters in item2.
But TextGrid file that I generated with MFA, there are duration information of each English characters in item2.

How could you generate TextGrid file with Korean character?
I used Hangul G2P and KSS-1.4. dataset. There are difference of my file and yours below.

Please let me know your method.
Thanks.

----------------------
안녕하세요, MFA로 만든 TextGrid 파일에 대한 질문입니다.
Jackson-Kang님의 G드라이브 내에 있는 TextGrid.zip를 보면, item2에서 duration 정보가 각 한국어 글자에 대해 나타나 있습니다.
그런데 제가 MFA를 통해 만든 TextGrid 파일을 보면 한글이 아닌 영문 phone으로 나타나 있더군요.

Jackson-Kang님처럼 한국어 phone으로 나타내는 방식은 어떻게 가능한 것인가요?
영문 phone으로 생성한 뒤 변환한 것인지, 아니면 처음부터 한글 character의 duration을 뽑는 방법을 쓰신 건지 알고 싶습니다.
참고로 전 MFA documentation page의 pretrained Hangul G2P 및 KSS-1.4. 데이터셋을 사용했습니다.
Jackson-Kang님과 제 파일의 차이를 비교할 수 있는 이미지를 아래 첨부했습니다.

답변 부탁드립니다.
감사합니다.

![image](https://user-images.githubusercontent.com/48062121/114666876-c17fb180-9d39-11eb-8a11-47c7aedfaee8.png)
![image](https://user-images.githubusercontent.com/48062121/114667011-e96f1500-9d39-11eb-95bf-512a2fe9cf15.png)

**Comment by Jackson-Kang** [comment]
@Wonbin-Jung 님께,

안녕하세요 @Wonbin-Jung 님.
먼저 저희 repository에 관심을 가져 주셔서 감사드립니다.

질문주신 사항에 답변드립니다.

Q) Jackson-Kang님처럼 한국어 phone으로 나타내는 방식은 어떻게 가능한 것인가요?
영문 phone으로 생성한 뒤 변환한 것인지, 아니면 처음부터 한글 character의 duration을 뽑는 방법을 쓰신 건지 알고 싶습니다.

A) duration을 추출할 때, MFA 공식 홈페이지에서 제공하는 pretrained G2p 모델을 사용하지 않았습니다. 대신, 아래와 같은 과정을 거쳐 MFA를 학습하였습니다.

     (1) rule-based G2pk(https://github.com/Kyubyong/g2pK)를 사용하여 한국어를 phoneme sequence로 변경
          ex) (transcript 예) 신라의 달밤은 참 예뻐요.      -> (phoneme sequence) 실라의 달빰은 참 예뻐요.    
     (2) jamo package의 h2j(https://github.com/jdongian/python-jamo)를 사용하여 (1)에서 얻은 phoneme sequence를 초,중,종성으로 분리
          ex)  (phoneme sequence) 실라의 달빰은 참 예뻐요.    ->   (decomposed phoneme sequence) ㅅㅣㄹㄹㅏㅇㅢ ....
     (3) word-phoneme mapping 관계가 정의된 dictionary를 만들고 MFA를 학습
          ex)   신라의     ㅅㅣㄹㄹㅏㅇㅢ
                  달밤은     ㄷㅏㄹㅃㅏㅁㅇㅡㄴ
                      ...                      ...


아래는 링크는 한국어 speech dataset으로 MFA를 학습하기 위해 작성한 코드입니다. 참고해보시고, 이해가 되지 않으시는 부분이 있다면 질문 남겨주세요.

https://github.com/Jackson-Kang/Korean-phoneme-dictionary-generator


감사합니다.

**Comment by Wonbin-Jung** [comment]
@Jackson-Kang 
안녕하세요 @Jackson-Kang 님, 친절한 답변 덕분에 질문한 부분이 이해되었습니다.
적어주신 링크의 phoneme dictionary generator를 사용하여 dictionary를 만들었는데, MFA training을 돌리려 하니 에러가 났습니다.
원인을 찾다가 Document/MFA 내의 words.txt나 phones.txt를 확인해보니 @Jackson-Kang 님이 만든 TextGrid의 word 및 phone과 차이가 있는 것 같더군요. Dictionary를 만들 때 wav 파일의 transcript 내 마침표, 물음표, 따옴표 같은 문장부호 등은 모두 지우고 적용한 것인가요?

감사합니다.

**Comment by Jackson-Kang** [comment]
> @Jackson-Kang
> 안녕하세요 @Jackson-Kang 님, 친절한 답변 덕분에 질문한 부분이 이해되었습니다.
> 적어주신 링크의 phoneme dictionary generator를 사용하여 dictionary를 만들었는데, MFA training을 돌리려 하니 에러가 났습니다.
> 원인을 찾다가 Document/MFA 내의 words.txt나 phones.txt를 확인해보니 @Jackson-Kang 님이 만든 TextGrid의 word 및 phone과 차이가 있는 것 같더군요. Dictionary를 만들 때 wav 파일의 transcript 내 마침표, 물음표, 따옴표 같은 문장부호 등은 모두 지우고 적용한 것인가요?
> 
> 감사합니다.

@Wonbin-Jung 님께,

transcript 내의 문장 부호는 제거하지 않은 채로 MFA를 run 했습니다.
말씀하신 이슈는, MFA version과도 연관이 있을 것으로 추정됩니다.

사용하신 MFA version이 어떻게 되시는지 알 수 있을까요?
저는 MFA version 1.0을 사용하였습니다.
MFA version 1.0은 말씀하신 사항으로 인해 문제가 발생하지 않았던 것으로 기억합니다.

감사합니다.

**Comment by Wonbin-Jung** [comment]
MFA 1.0.1.과 2.0.0.를 모두 사용해보았습니다.
1.0.1은 dictionary에 포함되지 않는 단어가 있다고 하고, 2.0.0.은 dictionary 관련 파일인L.fst 및 temp.fst가 생성되지 않는 문제가 있습니다.
우선 데이터셋 크기가 너무 커서 그런가 싶어 크기를 줄여서 시도 중입니다.
그래도 막히면 질문 새로 올리도록 하겠습니다.

답변 감사드립니다.

**Comment by Jackson-Kang** [comment]
> MFA 1.0.1.과 2.0.0.를 모두 사용해보았습니다.
> 1.0.1은 dictionary에 포함되지 않는 단어가 있다고 하고, 2.0.0.은 dictionary 관련 파일인L.fst 및 temp.fst가 생성되지 않는 문제가 있습니다.
> 우선 데이터셋 크기가 너무 커서 그런가 싶어 크기를 줄여서 시도 중입니다.
> 그래도 막히면 질문 새로 올리도록 하겠습니다.
> 
> 답변 감사드립니다.


@Wonbin-Jung 님께,

관련 사항은 dictionary를 생성하기 위해 제가 작성한 코드의 문제가 있을 가능성도 높다고 생각합니다. 저도 testcase를 만들어 검토를 해보고 결과를 공유드리겠습니다.

관련 문제가 빠른 시간내에 해결되기를 바랍니다.
감사드립니다.

**Comment by Wonbin-Jung** [comment]
안녕하세요 @Jackson-Kang 님,

데이터셋을 줄여서 시도해봐도 1.0.1. 버전은 dictionary에 포함되지 않는 word들이 있다고 하고, 2.0.0.은 돌아가지만 TextGrid 파일에 일부 문장부호들이 phone처럼 취급되서 들어가더군요.

1.0.1 버전의 문제는, 제 생각이 맞다면 포함되지 않는 단어들은 '가능하신지요', '가능하실까요', '가능하십니까'와 같은 단어들이었는데, dictionary에선 마침표나 물음표 같은 문장부호가 포함된 채로 들어가 있어 인식 못하는 것 같습니다.

2.0.0.의 문제는, '실례지만, 전화주신 고객님의 성함이 어떻게 되십니까?'라는 transcription을 받으면 아래 이미지와 같이 word에서는 문장 부호들이 제거되지만, phone에서는 그렇지 않습니다.
@Jackson-Kang 님의 TextGrid 파일에는 이런 부분들이 ""이나 "sp"로 표시되는데, 이 문제만 해결되면 아마 작동에 문제가 없을 것 같습니다.

혹시 참고가 될까 하여 글 남겼습니다. 진전이 있다면 다시 질문하도록 하겠습니다.
지속적인 확인 및 답변 감사드립니다.
![image](https://user-images.githubusercontent.com/48062121/115190005-5ad80a80-a122-11eb-841f-55bce10deaaf.png)
![image](https://user-images.githubusercontent.com/48062121/115190113-81964100-a122-11eb-87c3-18b0d788037e.png)

**Comment by Jackson-Kang** [comment]
> 안녕하세요 @Jackson-Kang 님,
> 
> 데이터셋을 줄여서 시도해봐도 1.0.1. 버전은 dictionary에 포함되지 않는 word들이 있다고 하고, 2.0.0.은 돌아가지만 TextGrid 파일에 일부 문장부호들이 phone처럼 취급되서 들어가더군요.
> 
> 1.0.1 버전의 문제는, 제 생각이 맞다면 포함되지 않는 단어들은 '가능하신지요', '가능하실까요', '가능하십니까'와 같은 단어들이었는데, dictionary에선 마침표나 물음표 같은 문장부호가 포함된 채로 들어가 있어 인식 못하는 것 같습니다.
> 
> 2.0.0.의 문제는, '실례지만, 전화주신 고객님의 성함이 어떻게 되십니까?'라는 transcription을 받으면 아래 이미지와 같이 word에서는 문장 부호들이 제거되지만, phone에서는 그렇지 않습니다.
> @Jackson-Kang 님의 TextGrid 파일에는 이런 부분들이 ""이나 "sp"로 표시되는데, 이 문제만 해결되면 아마 작동에 문제가 없을 것 같습니다.
> 
> 혹시 참고가 될까 하여 글 남겼습니다. 진전이 있다면 다시 질문하도록 하겠습니다.
> 지속적인 확인 및 답변 감사드립니다.
> ![image](https://user-images.githubusercontent.com/48062121/115190005-5ad80a80-a122-11eb-841f-55bce10deaaf.png)
> ![image](https://user-images.githubusercontent.com/48062121/115190113-81964100-a122-11eb-87c3-18b0d788037e.png)



@Wonbin-Jung 님께,


안녕하세요 @Wonbin-Jung 님.

MFA로부터 추출한 TextGrid에서, 실질적으로 사용되는 부분은 phone sequence들만 고려됩니다.
duration 추출에 성공하셔서 올려주신 두번째 이미지와 같은 TextGrid 추출에 성공하셨다면, 바로 사용하셔도 될 듯 합니다.

오히려, ","와 "\~"등이 포함된 TextGrid가 제가 업로드한 (",", "\~" 등이 제거된) TextGrid에 비해 더욱 자연스러운 발화를 생성할 가능성이 높다고 판단됩니다.

우선 생성하신 TextGrid를 갖고 FastSpeech2를 run해보시는 것을 권장드립니다.


문제가 생기면, 다시 말씀주세요.
제가 아는 한도 내에서, 최대한 돕겠습니다.

감사합니다.

**Comment by Wonbin-Jung** [comment]
MFA 2.0.0를 통한 학습이 잘 되었습니다.
좋은 코드 구현 및 상세한 답변 감사드립니다.

**Comment by Jackson-Kang** [comment]
> MFA 2.0.0를 통한 학습이 잘 되었습니다.
> 좋은 코드 구현 및 상세한 답변 감사드립니다.

@Wonbin-Jung 님게,


문제가 해결되어 다행입니다.

본 repository가 도움이 되었으면 좋겠습니다.
감사합니다.
